### ISSUE TITLE
Говно

### ISSUE THREAD

**Issue by vraestoren** [D4rkwat3r/Amino-Antiraid#1]
Напиши "Урааа зион я твой фанат 😀😀😀😀😊😀😊😀😊😀😊😀😊😀😊😀" если твоя мать свинья

**Comment by D4rkwat3r** [comment]
> Говном было говном и осталось что и ожидалось от дрочватера который юзает срапи ротатор.

Урааа зион я твой фанат 😀😀😀😀😊😀😊😀😊😀😊😀😊😀😊😀
